<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-08 at 17:39:10.
 */
class NavigationControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var NavigationController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new NavigationController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers NavigationController::invoke
     * @todo   Implement testInvoke().
     */
    public function testInvoke() {
        // Remove the following lines when you implement this test.
        $this->testGestioneGET();
    }

    /**
     * @covers NavigationController::gestioneGET
     * @todo   Implement testGestioneGET().
     */
    public function testGestioneGET() {
        // Remove the following lines when you implement this test.
        $this->object->gestioneGET("searchStays");
    }

    /**
     * @covers NavigationController::gestionePOST
     * @todo   Implement testGestionePOST().
     */
    public function testGestionePOST() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
