<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-08 at 17:11:05.
 */
class SearchControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var SearchController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SearchController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers SearchController::searchJourneys
     * @todo   Implement testSearchJourneys().
     */
    public function testSearchJourneys() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchController::searchItineraries
     * @todo   Implement testSearchItineraries().
     */
    public function testSearchItineraries() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchController::searchStays
     * @todo   Implement testSearchStays().
     */
    public function testSearchStays() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchController::searchActivities
     * @todo   Implement testSearchActivities().
     */
    public function testSearchActivities() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchController::searchTransport
     * @todo   Implement testSearchTransport().
     */
    public function testSearchTransport() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchController::searchMyItineraries
     * @todo   Implement testSearchMyItineraries().
     */
    public function testSearchMyItineraries() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchController::searchMyJourneys
     * @todo   Implement testSearchMyJourneys().
     */
    public function testSearchMyJourneys() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchController::search
     * @todo   Implement testSearch().
     */
    public function testSearch() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchController::getJourney
     * @todo   Implement testGetJourney().
     */
    public function testGetJourney() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchController::getItinerary
     * @todo   Implement testGetItinerary().
     */
    public function testGetItinerary() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
