<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-08 at 17:11:20.
 */
class AJConnectionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AJConnection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AJConnection;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AJConnection::registra
     * @todo   Implement testRegistra().
     */
    public function testRegistra() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AJConnection::newCreator
     * @todo   Implement testNewCreator().
     */
    public function testNewCreator() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AJConnection::verificaLogin
     * @todo   Implement testVerificaLogin().
     */
    public function testVerificaLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AJConnection::executeQuery
     * @todo   Implement testExecuteQuery().
     */
    public function testExecuteQuery() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AJConnection::executeNonQuery
     * @todo   Implement testExecuteNonQuery().
     */
    public function testExecuteNonQuery() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AJConnection::beginTransaction
     * @todo   Implement testBeginTransaction().
     */
    public function testBeginTransaction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AJConnection::commit
     * @todo   Implement testCommit().
     */
    public function testCommit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AJConnection::rollback
     * @todo   Implement testRollback().
     */
    public function testRollback() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AJConnection::lastInsertedId
     * @todo   Implement testLastInsertedId().
     */
    public function testLastInsertedId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AJConnection::close
     * @todo   Implement testClose().
     */
    public function testClose() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
