<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-08 at 17:12:06.
 */
class AccomodationTemplateTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AccomodationTemplate
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AccomodationTemplate;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AccomodationTemplate::serialize
     * @todo   Implement testSerialize().
     */
    public function testSerialize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccomodationTemplate::unserialize
     * @todo   Implement testUnserialize().
     */
    public function testUnserialize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccomodationTemplate::getId
     * @todo   Implement testGetId().
     */
    public function testGetId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccomodationTemplate::getAddress
     * @todo   Implement testGetAddress().
     */
    public function testGetAddress() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccomodationTemplate::getAccomodationType
     * @todo   Implement testGetAccomodationType().
     */
    public function testGetAccomodationType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccomodationTemplate::getDescription
     * @todo   Implement testGetDescription().
     */
    public function testGetDescription() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccomodationTemplate::getCategory
     * @todo   Implement testGetCategory().
     */
    public function testGetCategory() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccomodationTemplate::getName
     * @todo   Implement testGetName().
     */
    public function testGetName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccomodationTemplate::getLink
     * @todo   Implement testGetLink().
     */
    public function testGetLink() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccomodationTemplate::getPhoto
     * @todo   Implement testGetPhoto().
     */
    public function testGetPhoto() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccomodationTemplate::getLocation
     * @todo   Implement testGetLocation().
     */
    public function testGetLocation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccomodationTemplate::setAddress
     * @todo   Implement testSetAddress().
     */
    public function testSetAddress() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccomodationTemplate::setAccomodationType
     * @todo   Implement testSetAccomodationType().
     */
    public function testSetAccomodationType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccomodationTemplate::setDescription
     * @todo   Implement testSetDescription().
     */
    public function testSetDescription() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccomodationTemplate::setCategory
     * @todo   Implement testSetCategory().
     */
    public function testSetCategory() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccomodationTemplate::setName
     * @todo   Implement testSetName().
     */
    public function testSetName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccomodationTemplate::setLink
     * @todo   Implement testSetLink().
     */
    public function testSetLink() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccomodationTemplate::setPhoto
     * @todo   Implement testSetPhoto().
     */
    public function testSetPhoto() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccomodationTemplate::setLocation
     * @todo   Implement testSetLocation().
     */
    public function testSetLocation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccomodationTemplate::saveIntoDB
     * @todo   Implement testSaveIntoDB().
     */
    public function testSaveIntoDB() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
