<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-08 at 17:12:06.
 */
class AccomodationTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Accomodation
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Accomodation;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Accomodation::serialize
     * @todo   Implement testSerialize().
     */
    public function testSerialize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Accomodation::unserialize
     * @todo   Implement testUnserialize().
     */
    public function testUnserialize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Accomodation::getId
     * @todo   Implement testGetId().
     */
    public function testGetId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Accomodation::getNumeroDisponibilita
     * @todo   Implement testGetNumeroDisponibilita().
     */
    public function testGetNumeroDisponibilita() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Accomodation::getStartDate
     * @todo   Implement testGetStartDate().
     */
    public function testGetStartDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Accomodation::getDuration
     * @todo   Implement testGetDuration().
     */
    public function testGetDuration() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Accomodation::getEndDate
     * @todo   Implement testGetEndDate().
     */
    public function testGetEndDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Accomodation::getStartLocation
     * @todo   Implement testGetStartLocation().
     */
    public function testGetStartLocation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Accomodation::getEndLocation
     * @todo   Implement testGetEndLocation().
     */
    public function testGetEndLocation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Accomodation::getType
     * @todo   Implement testGetType().
     */
    public function testGetType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Accomodation::setNumeroDisponibilita
     * @todo   Implement testSetNumeroDisponibilita().
     */
    public function testSetNumeroDisponibilita() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Accomodation::setStartDate
     * @todo   Implement testSetStartDate().
     */
    public function testSetStartDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Accomodation::setEndDate
     * @todo   Implement testSetEndDate().
     */
    public function testSetEndDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Accomodation::setStartLocation
     * @todo   Implement testSetStartLocation().
     */
    public function testSetStartLocation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Accomodation::setEndLocation
     * @todo   Implement testSetEndLocation().
     */
    public function testSetEndLocation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Accomodation::setDuration
     * @todo   Implement testSetDuration().
     */
    public function testSetDuration() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Accomodation::saveIntoDB
     * @todo   Implement testSaveIntoDB().
     */
    public function testSaveIntoDB() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Accomodation::addComponent
     * @todo   Implement testAddComponent().
     */
    public function testAddComponent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Accomodation::getComponentsOfType
     * @todo   Implement testGetComponentsOfType().
     */
    public function testGetComponentsOfType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Accomodation::isComposite
     * @todo   Implement testIsComposite().
     */
    public function testIsComposite() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Accomodation::removeComponent
     * @todo   Implement testRemoveComponent().
     */
    public function testRemoveComponent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
