<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-08 at 17:15:15.
 */
class ConcreteUserComponentTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ConcreteUserComponent
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ConcreteUserComponent;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ConcreteUserComponent::__sleep
     * @todo   Implement test__sleep().
     */
    public function test__sleep() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::__wakeup
     * @todo   Implement test__wakeup().
     */
    public function test__wakeup() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::getRole
     * @todo   Implement testGetRole().
     */
    public function testGetRole() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::getName
     * @todo   Implement testGetName().
     */
    public function testGetName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::getSurname
     * @todo   Implement testGetSurname().
     */
    public function testGetSurname() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::getAddress
     * @todo   Implement testGetAddress().
     */
    public function testGetAddress() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::getTelephone
     * @todo   Implement testGetTelephone().
     */
    public function testGetTelephone() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::getMail
     * @todo   Implement testGetMail().
     */
    public function testGetMail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::getSearchResultJourney
     * @todo   Implement testGetSearchResultJourney().
     */
    public function testGetSearchResultJourney() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::getSearchResultItinerary
     * @todo   Implement testGetSearchResultItinerary().
     */
    public function testGetSearchResultItinerary() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::getSearchResultStay
     * @todo   Implement testGetSearchResultStay().
     */
    public function testGetSearchResultStay() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::getSearchResultActivity
     * @todo   Implement testGetSearchResultActivity().
     */
    public function testGetSearchResultActivity() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::setJourneySearchResult
     * @todo   Implement testSetJourneySearchResult().
     */
    public function testSetJourneySearchResult() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::setItinerarySearchResult
     * @todo   Implement testSetItinerarySearchResult().
     */
    public function testSetItinerarySearchResult() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::setStaySearchResult
     * @todo   Implement testSetStaySearchResult().
     */
    public function testSetStaySearchResult() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::setActivitySearchResult
     * @todo   Implement testSetActivitySearchResult().
     */
    public function testSetActivitySearchResult() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::getJourney
     * @todo   Implement testGetJourney().
     */
    public function testGetJourney() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::getItinerary
     * @todo   Implement testGetItinerary().
     */
    public function testGetItinerary() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::getStay
     * @todo   Implement testGetStay().
     */
    public function testGetStay() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::getActivity
     * @todo   Implement testGetActivity().
     */
    public function testGetActivity() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::getAccomodation
     * @todo   Implement testGetAccomodation().
     */
    public function testGetAccomodation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::getBrick
     * @todo   Implement testGetBrick().
     */
    public function testGetBrick() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::getBrickActivity
     * @todo   Implement testGetBrickActivity().
     */
    public function testGetBrickActivity() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::getBrickAccomodation
     * @todo   Implement testGetBrickAccomodation().
     */
    public function testGetBrickAccomodation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::createItinerary
     * @todo   Implement testCreateItinerary().
     */
    public function testCreateItinerary() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::removeItinerary
     * @todo   Implement testRemoveItinerary().
     */
    public function testRemoveItinerary() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::searchStays
     * @todo   Implement testSearchStays().
     */
    public function testSearchStays() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::searchTransport
     * @todo   Implement testSearchTransport().
     */
    public function testSearchTransport() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::searchActivities
     * @todo   Implement testSearchActivities().
     */
    public function testSearchActivities() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::addBrick
     * @todo   Implement testAddBrick().
     */
    public function testAddBrick() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::modifyStay
     * @todo   Implement testModifyStay().
     */
    public function testModifyStay() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::removeBrick
     * @todo   Implement testRemoveBrick().
     */
    public function testRemoveBrick() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::addActivity
     * @todo   Implement testAddActivity().
     */
    public function testAddActivity() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::addActivityFromTemplate
     * @todo   Implement testAddActivityFromTemplate().
     */
    public function testAddActivityFromTemplate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::modifyActivity
     * @todo   Implement testModifyActivity().
     */
    public function testModifyActivity() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::removeActivity
     * @todo   Implement testRemoveActivity().
     */
    public function testRemoveActivity() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::addAccomodation
     * @todo   Implement testAddAccomodation().
     */
    public function testAddAccomodation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::modifyAccomodation
     * @todo   Implement testModifyAccomodation().
     */
    public function testModifyAccomodation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConcreteUserComponent::removeAccomodation
     * @todo   Implement testRemoveAccomodation().
     */
    public function testRemoveAccomodation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
