<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-08 at 17:11:45.
 */
class StaySearchResultTest extends PHPUnit_Framework_TestCase {

    /**
     * @var StaySearchResult
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new StaySearchResult;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers StaySearchResult::__sleep
     * @todo   Implement test__sleep().
     */
    public function test__sleep() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers StaySearchResult::__wakeup
     * @todo   Implement test__wakeup().
     */
    public function test__wakeup() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers StaySearchResult::searchStay
     * @todo   Implement testSearchStay().
     */
    public function testSearchStay() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers StaySearchResult::searchTransport
     * @todo   Implement testSearchTransport().
     */
    public function testSearchTransport() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers StaySearchResult::fetchObject
     * @todo   Implement testFetchObject().
     */
    public function testFetchObject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers StaySearchResult::getObject
     * @todo   Implement testGetObject().
     */
    public function testGetObject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
